[package]
name = "swayidle_switch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
expanduser = "1.2.2"
notify-rust = "4.11.0"
sysinfo = "0.33.1"
